### ISSUE TITLE
Working Sets

### ISSUE THREAD

**Issue by aaiezza** [ssi-schaefer/lcdsl#30]
I don't know if you are familiar with the Eclipse working sets, but it's a great way to organize your projects in an Eclipse workspace in the Project Explorer view.

It would cool to be able to toggle a filter for the launch configurations by selected project. Or to be able to toggle organizing them by working set or project instead of type.

**Comment by mduft** [comment]
This is definitely not what you are asking for, but you can in the meantime achieve "better" grouping of configurations by using the 'qualified' keyword for the configuration - it will simply prefix the project name to the launch configuration.

**Comment by haubi** [comment]
Not sure if there's an unresolved feature request here still: If there is, please reopen and elaborate a little.
