### ISSUE TITLE
Missing latest version of org.eclipse.debug.ui.launchview

### ISSUE THREAD

**Issue by glatuske** [ssi-schaefer/lcdsl#39]
In the latest code some classes out of a newer version of org.eclipse.debug.ui.launchview are used. But there is no repository providing this plugin. Any idea where to get it?

**Comment by mduft** [comment]
Sorry for the delay. The launch configuration view has been moved and incorporated into Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=513735 The code in the LcDSL repository has been adapted to the slightly changed API already, the update site not yet. Once Eclipse 2021-12 including the launch configuration view has been released, I will update the update site, features, marketplace listing, etc. Until then, you can use the provided binaries, or - in case you need the code - use commit ff90a8486145e3e1c762688090f8bbfe00bae5d3

**Comment by glatuske** [comment]
Waiting for Eclipse 2021-12 would be sufficient for me.
