### ISSUE TITLE
Startlevels for workspacebundles

### ISSUE THREAD

**Issue by EaseRider** [ssi-schaefer/lcdsl#40]
I have some startLevels defined in my product:
```
<configurations>
      <plugin id="org.eclipse.core.runtime" autoStart="true" startLevel="1" />
      <plugin id="org.eclipse.equinox.ds" autoStart="true" startLevel="1" />
      <plugin id="org.eclipse.equinox.event" autoStart="true" startLevel="2" />
      <plugin id="my.plugin" autoStart="true" startLevel="3" />
   </configurations>
```
But they seem not to have any impact. The important point is for the plugin from workspace:
`<setEntry value="my.plugin@default:default"/>`
So that I need to define at least the my.plugin startlevel in the lc to run my project properly. 

Also the org.eclipse.equinox.ds does not get any starting level:
`<setEntry value="org.eclipse.equinox.ds*[version]@default:default"/>`

And org.eclipse.core.runtime gets another start level:
`<setEntry value="org.eclipse.core.runtime*3.20.100.v20210111-0815@0:true"/>`

The lc looks like this:
```
explicit eclipse configuration MyProduct {
	product my.product;
	content-provider "${workspace_loc:my.product}/product.product";
	//plugin my.plugin startlevel 3 autostart;
}
```

**Comment by glatuske** [comment]
Currently configuration for plugins (start levels, auto start) is not extracted out of a referenced product file. Only VM and program arguments are transferred from product configuration to launch configuration.

But it's a good idea. Maybe I find some time to contribute this.

**Comment by glatuske** [comment]
I have created a PR #44 which adds start level and auto start configured in the .product file to the launch configuration. If you configure a plugin in your .lc file the start level and auto start configured there has still precedence.

**Comment by glatuske** [comment]
PR #44 has been merged. @mduft when will you provide a new update site?

**Comment by mduft** [comment]
I just updated the 'lcdsl-latest' update site at https://mduft.github.io/lcdsl-latest/ - the site is now targeted at Eclipse 2021-12, since this has the launch configuration view already in it. If you still need an older Eclipse, you will need to grab the view (only!) from https://mduft.github.io/lcdsl-legacy/ and LcDSL from https://mduft.github.io/lcdsl-latest/ - that should work (untested though).

**Comment by glatuske** [comment]
I have tested latest updatesite (btw. thanks for the providing it that fast!). Reading start level and auto start from product file works for me. I'm also fine with providing it only to Eclipse 2021-12.

**Comment by mduft** [comment]
Thanks for the retest :)
