### ISSUE TITLE
Test class not accepting all JUnit5 variants

### ISSUE THREAD

**Issue by frankbenoit** [ssi-schaefer/lcdsl#50]
In the LCDSCL the block
````
Test {
    class my.TestClass;
}
````
does not accept all JUnit5 test classes.

E.g. in JUnit5 test class/method can be non-public, but package visible only. Please consider this example:

````
class TestClass {
    class Base {
        @Test
        void testMethod1() {}
        @Test
        void testMethod2() {}
    }
    @Nested
    class Variant1 extends Base {
        // configuration only, no test method
    }
    @Nested
    class Variant2 extends Base {
        // configuration only, no test method
    }
}
````

**Comment by mduft** [comment]
True, LcDSL currently only supports the JUnit Plugin Test Type from PDE, and the SWTBot Junit Tests. Additional support can be added (... when time permits and/or somebody cares to contribute ;)).

**Comment by Bananeweizen** [comment]
@frankbenoit Anything beyond non-public? That has been fixed in https://github.com/ssi-schaefer/lcdsl/pull/69.
