### ISSUE TITLE
Application `[No Application] - Headless Mode` unsupported. - Should be default

### ISSUE THREAD

**Issue by jgsuess** [ssi-schaefer/lcdsl#58]
In the Junit Runner application, there is a setting to run the built-in Eclipse JUnit runner. It hides behind a drop-down setting of `[No Application] - Headless Mode`. It would be nice to include this setting or even make this the default. I am unsure how else I can use the DSL without this at the moment - the validation fails as the editor does not know about this.

The default application name is `org.eclipse.pde.junit.runtime.application` for headless, and something with `UI` for running with widgets. It would be great if you could add this, as headless tests are very common.

**Comment by kapexx** [comment]
Headless mode seems to be supported. I just tried it for a junit5 plugin test in Eclipse 2023-03. The editor suggestions contain applications named `org.eclipse.pde.junit.runtime.coretestapplication`, `org.eclipse.pde.junit.runtime.uitestapplication` and `org.eclipse.pde.junit.runtime.nonuithreadtestapplication`.

When using `application org.eclipse.pde.junit.runtime.coretestapplication`, the generated launch config has `[No Application] - Headless Mode` selected and works as expected for me.

**Comment by haubi** [comment]
Changing some _default_ behavior really requires good reasoning as well as release management (major release), communication and what not, so I'm quite hesitant here.
The answer from @kapexx (thanks!) lets me believe that headless mode is supported "good enough". If not, please reopen and elaborate a little.
