### ISSUE TITLE
Compile error due to using API 11, but 1.8 on classpath

### ISSUE THREAD

**Issue by Bananeweizen** [ssi-schaefer/lcdsl#67]
The project is currently in an inconsistent state and does not compile, if the JDK is setup correctly. It uses methods from Java 11 (List.of(...)), but compiles with 1.8 and has BREE 1.8. Would you prefer fixing the code to be 1.8 compatible again, or rather upgrade BREE and jdt settings to 11 (what I would very much prefer)?

**Comment by mduft** [comment]
Heh, yeah, it is developed in a 11 environment, so that can happen unfortunately. I would prefer 11, yes.
